### ISSUE TITLE
components inside InfiniteListItem not updating

### ISSUE THREAD

**Issue by mattybow** [ganmor/react-infinite-list#1]
The child components wrapped in the `InfiniteListComponent` in the `InfiniteListItem` uses `shouldComponentUpdate` that looks at the `rendered` prop but that insulates the child wrapped inside from an update due to a change in it's props.

Here's a possible solution in `InfiniteListItem.shouldComponentUpdate`:
current:

``` javascript
shouldComponentUpdate = this.props.rendered != nextProps.rendered;
```

proposed:

``` javascript
shouldComponentUpdate = (this.props.rendered != nextProps.rendered || JSON.stringify(this.props.children.props) !== JSON.stringify(nextProps.children.props) );
```

**Comment by ganmor** [comment]
Did you try with the current version in master ?

The actual implementation is this : 

```
shouldComponentUpdate = (this.props.rendered != nextProps.rendered) || nextProps.rendered;
```

This just avoid  items not currently rendered from being updated, so this is actually intended.
I have updated the example with a shuffle button, that changes  the inner elements color.

**Comment by ganmor** [comment]
Closing since code has been refactored and does not require the shouldComponentUpdate  method anymore
